CREATE TABLE tools (
id INTEGER PRIMARY KEY,
 title TEXT NOT NULL UNIQUE,
 link TEXT NOT NULL,
 description TEXT,
 tags TEXT[]
);

ALTER TABLE IF EXISTS tools
 ALTER COLUMN id
 ADD GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1);